version: "3.8"

services:
  redis-stack:
    container_name: redis-stack-dev
    image: redis/redis-stack:6.2.6-v4

  api:
    # This starts GUnicorn with live-reload
    command: /fastapi_redis_om/backend/start-reload.sh
    container_name: fastapi-dev
    image: fastapi
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/fastapi_redis_om/backend